apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o7c7hrtj2-go
  janus-idp.io/tekton: o7c7hrtj2-go
  backstage.io/kubernetes-id: o7c7hrtj2-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7c7hrtj2-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
