apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: o7c7hrtj2-go-gitops
  description: This is GitOps manifest for o7c7hrtj2-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: o7c7hrtj2-go
    janus-idp.io/tekton: o7c7hrtj2-go 
    backstage.io/kubernetes-id: o7c7hrtj2-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:o7c7hrtj2-go
